### PR TITLE
Switched from 128 to 256 AES CBC

### PR DESCRIPTION
**Pull request by chiedo**
Thanks for putting together this awesome script.

Maybe I'm missing something but is there a reason you're using 128 instead of 256?

If not, I saved you about 2 seconds with this PR. LOL! :)

### CODE REVIEW

**Comment by Nyr** [comment]
The question to me is why would you want a cipher with worse performance when `AES-128-CBC` is perfectly fine and secure. 

This has been discussed a lot of times already, last was just [a week ago](https://github.com/Nyr/openvpn-install/issues/166).

**Comment by chiedo** [comment]
Thanks for the quick response @Nyr, I didn't think about the performance.

**Comment by DonZheng** [comment]
Hi @Nyr,

I bumped into this thread and learned that AES-128-CBC may perform better than 256. So I tried testing 128 and modified your script to give both server.conf and client.ovpn this:
`auth SHA512
cipher AES-128-CBC
`
But from system log, it seems the 256-GCM is still negotiated between server and client. Is there anything I did wrong here? How can I enforce/enable 128 here?

(System environment: Ubuntu 16.04)

Thanks in advance for your guidance.

**Comment by Nyr** [comment]
Be advised that the cipher is usually not a real world factor in OpenVPN performance over the internet.

> I did wrong here?

No. Use `ncp-disable` if you don't want the cipher to be negotiated.

**Comment by DonZheng** [comment]
Dear @Nyr 

Your quick reply has been greatly appreciated. 👍 

Just one dummy question, I'm about to use below three lines on both client.ovpn and server.conf
`ncp-disable`
`auth SHA512`
`cipher AES-128-CBC`

Is that correct? Is there anything else I need to twist? 

Sorry for my dummy question, but thank you in advance for putting up with me.

**Comment by Nyr** [comment]
That's fine for what you want.

Using `ncp-disable` in the client only would be enough to disable negotiation.

**Comment by DonZheng** [comment]
Thanks again for your advice, @Nyr .

I will test it out and report back. Hopefully my dummy question can contribute to your community in its own way. (maybe serve other dummy users like myself. :-)

**Comment by DonZheng** [comment]
Hi @Nyr ,

Your previous advice has been echoing in my head: `cipher is usually not a real world factor in OpenVPN performance over the internet.`

I wonder if you could please share some specific guidance on key elements users should look into?

In my specific case, I am running your script on VPS (ubuntu 16.04), and allow my fellow users to connect via android clients. With a 100mbps port, I can only get 50% of the throuput.
I'm not sure whether I should modify MTU, sndbuf/recvbuf, txqueuelen for better performance?

Your thoughts?

**Comment by Nyr** [comment]
@DonZheng the conversation is going a bit off topic, but I'll try to explain briefly:

Generalising, any modern processor will be able to do at the very least tens of MB/s with any of the mentioned ciphers, that's why I said that the cipher performance is unlikely an issue. An exception would be if your CPU, being shared with other VPS customers, is getting hammered badly. That would be rare if you are using a decent provider.

If you are getting about 50 mbps with OpenVPN over the internet, that's an average result, not bad. There are many contributing factors such as:
- Client and server CPU
- Network congestion and distance between client and server
- Prioritization (or the opposite) of that kind of traffic by your ISP
- Your clients are apparently connecting over Wi-Fi

There are other factors to consider, but the bottom line is that your performance is not bad, specially if the clients are smartphones. Just so you get an idea, my OpenVPN connection from Spain to a server in Bulgaria usually does 2-3 MB/s and even if I use a server in France I'll struggle to push more than 5-6 MB/s from my computer on a FTTH connection.

**Comment by DonZheng** [comment]
Dear @Nyr ,

REALLY appreciate your enlightening response. 👍 👍 👍 👍 👍 

As you advised, maybe I should try a dedicated server in the near future.

**Pull request closed without merging**
