### PR TITLE
update shabang

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Use `env` to determine path of bash will be much portable.

### CODE REVIEW

**Comment by Nyr** [comment]
All supported distros have bash available at `/bin/bash` so this is not needed.

**Comment by PeterDaveHello** [comment]
Not that problem, what if I wanna use a self-built bash instead of system-wide?
Make it much portable won't bite I think :smile:

**Comment by Nyr** [comment]
Using `env` has other security implications too. System-wide bash would work perfectly with the script.

**Comment by akashseo963** [comment]
Thanks for Nice and Informative Post. This article is really contains lot more information about This Topic.  - 
<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Packers and Movers Chennai">Packers and Movers Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers Mumbai">Packers and Movers Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Packers and Movers Noida">Packers and Movers Noida</a>

**Comment by akashseo963** [comment]
This article is really fantastic and thanks for sharing the valuable post.
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Packers and Movers Delhi">Packers and Movers Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>

**Comment by akashseo963** [comment]
Thanks for sharing your info. I really appreciate your efforts and I will be waiting for your further write
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Packers and Movers Faridabad">Packers and Movers Faridabad</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Packers and Movers Thane">Packers and Movers Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Packers and Movers Navi Mumbai">Packers and Movers Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Packers and Movers Ghaziabad">Packers and Movers Ghaziabad</a>

**Comment by akashseo963** [comment]
Thanks for post this helpful post - Please visit for More information about -
<a href="http://www.dteller.in/packers-and-movers-gurgaon/" title="Packers and Movers Gurgaon">Packers and Movers Gurgaon</a>
<a href="http://www.dteller.in/packers-and-movers-bangalore/" title="Packers and Movers Bangalore">Packers and Movers Bangalore</a>
<a href="http://www.dteller.in/packers-and-movers-hyderabad/" title="Packers and Movers Hyderabad">Packers and Movers Hyderabad</a>
<a href="http://www.dteller.in/packers-and-movers-pune/" title="Packers and Movers Pune">Packers and Movers Pune</a>

**Pull request closed without merging**
