### PR TITLE
fix net.ipv4.ip_forward settings

### PR DESCRIPTION
**Pull request by hhktony**
centos7 `# net.ipv4.ip_forward=1`

### CODE REVIEW

**Comment by Nyr** [comment]
Please, don't open pull requests for untested crap.

Anyway, I don't think anything is wrong with the current approach so a fix isn't needed to start with.

**Comment by hhktony** [comment]
https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh#L295

if ! grep -q "net.ipv4.ip_forward=1" "/etc/sysctl.conf"
if ! grep -q "# net.ipv4.ip_forward=1" "/etc/sysctl.conf"

2016-09-06 18:27 GMT+08:00 Nyr <notifications@github.com>:

**Comment by Nyr** [comment]
Are you trying to say that the following line exists but is commented in some CentOS 7 image?

`# net.ipv4.ip_forward=1`

If so, please let me know what's the provider. This is not the default.

**Comment by Nyr** [comment]
I have pushed 791c54786c2cb2f6500e20f931b33fbb234a8ce4 anyway.

The previous approach was too complex for a very simple change.

**Pull request closed without merging**
