### PR TITLE
Adding autodetection of the external IP using ifconfig.co

### PR DESCRIPTION
**Pull request by nachootal**
Just adding an auto detection of the external ip using ifconfig.co

### CODE REVIEW

**Comment by nachootal** [comment]
Just adding an auto detection of the external ip using ifconfig.co

**Comment by Nyr** [comment]
This pull request breaks the installer in the following circumstances:

- Systems behind NAT
- Systems preferring IPv6 over IPv4
- curl is not available

**Comment by nachootal** [comment]
As far as I see this, it's only an advice on an IP address and code wise it's only used when an internal IPv4 is detected. This would still make it through the first two points imho.

The third one, I agree, it will break in case curl is not present. I don't know whether curl is installed in the base system in the case of debian, centos and fedora and we can assume that it will be there. I could add this to the list of needed software on the script. What do you think about this?.

**Comment by Nyr** [comment]
Sorry, I didn't understand your pull request correctly the first time, forget about my first point.

Still, there are other problems:
- In many cases your proposed commit would end up suggesting the user an IPv6 which is wrong and this is easily avoidable. For example, it could be fixed by forcing curl to perform the request over IPv4 or using `ipv4.icanhazip.com`.
- You are proposing to add curl as a dependency, but this is not needed and you can take a look in the script and see how this is addressed when downloading easy-rsa. `curl` is not installed by default everywhere and there is no need to depend on it.

There are other problems but the main one is that guessing which public IP address needs to be set up can be more confusing for the user that manually entering the address, and that's why this was not done your way.
For example, when this project launched years ago, the most common case for NAT servers were hosts which accepted inbound connections in let's say `12.34.56.78` and used `12.34.56.79` for outbound. For me, suggesting a wrong IP address to the user feels worse than not suggesting anything at all. Specially when the wrong suggestion can be very similar to the right one. I would need to evaluate if the NAT VPS available nowadays are still using my described setup or things have changed.

I'm open to someone else checking this for me, at the very least we would need data from the 3 LowEndSpirit providers. If the situation has changed favorably for us, I'm open to change this, home servers behind a NAT and the big cloud providers don't usually have this problem.

**Pull request closed without merging**
