### PR TITLE
added http://censurfridns.dk/

### PR DESCRIPTION
**Pull request by joewhat**

### CODE REVIEW

**Comment by Nyr** [comment]
Not merging this.

Main reason although not the only one, is because even if the resolver is anycast, it lacks geographic diversity.

All of the other resolvers currently offered are also "censorship free".

**Comment by joewhat** [comment]
okay - great job on the script.

**Comment by Nyr** [comment]
To be clear about my criteria for adding new resolvers, they need to:

- Be anycast
- Have a reasonable amount of PoPs around the world 
- Provide unfiltered responses
- Be run by a trustable organization and have a proven track record

There are surprisingly few services fitting this criteria, all of which I know of had been included as choices.

**Comment by joewhat** [comment]
okay, thank you

**Pull request closed without merging**
