### PR TITLE
Add asking for password: CA, server-cert and client-cert

### PR DESCRIPTION
**Pull request by andreev-g**
Add additional switches:
1) For setup CA password
2) For setup server's certificate password
3) For setup client's certificate password

### CODE REVIEW

**Comment by bugrevealingbme** [comment]
How to setup password?

**Comment by bugrevealingbme** [comment]
How to setup password?

**Comment by andreev-g** [comment]
> How to setup password?

By questions while script running

**Comment by bugrevealingbme** [comment]
> > How to setup password?
> 
> By questions while script running

It does not ask for any password when connecting to the server. I tried editing the config but it doesn't work. I want to ask for password when connecting to server

**Comment by andreev-g** [comment]
> > > How to setup password?
> > 
> > By questions while script running
> 
> It does not ask for any password when connecting to the server. I tried editing the config but it doesn't work. I want to ask for password when connecting to server

you dont need to edit .ovpn config.
maybe your OpenVPN client doesnt provide configs with password?
or maybe you skip password setup when script executing?

and last question: doesnt work at all or your ovpn client doesnt asking you for password?

**Comment by bugrevealingbme** [comment]
I can connect. But I have a VPN app and I want to put user-pass on servers

**Comment by andreev-g** [comment]
> I can connect. But I have a VPN app and I want to put user-pass on servers

as i understand, your problem doesnt related to script executing, but related to passing password when ovpn server is starting?

i cant remember which command i used for solving this problem.
but when i setup my vpn-server on ubuntu, system told me this command by broadcast message to console.

**Comment by andreev-g** [comment]
> > I can connect. But I have a VPN app and I want to put user-pass on servers
> 
> as i understand, your problem doesnt related to script executing, but related to passing password when ovpn server is starting?
> 
> i cant remember which command i used for solving this problem. but when i setup my vpn-server on ubuntu, system told me this command by broadcast message to console.

try this:
$ sudo systemd-tty-ask-password-agent

**Comment by bugrevealingbme** [comment]
I can connect no problem. I just want to set a password for the server. I want to login with: auth-user-pass

**Comment by andreev-g** [comment]
> I can connect no problem. I just want to set a password for the server. I want to login with: auth-user-pass

tell me how you solved the problem when you figure it out

**Comment by bugrevealingbme** [comment]
> > I can connect no problem. I just want to set a password for the server. I want to login with: auth-user-pass
> 
> tell me how you solved the problem when you figure it out

I found this https://medium.com/@vantintttp/how-to-setup-openvpn-authentication-by-username-and-password-589a97cafd8b 

I didn't know how to use

**Comment by Nyr** [comment]
Sorry but this will not be merged into the master branch. You can search for previous discussion on the matter.

**Pull request closed without merging**
