### PR TITLE
added function to type a own DNS server

### PR DESCRIPTION
**Pull request by Lukas-Heiligenbrunner**
I added the (for me) useful function to type a own dns server...

lg. lukas

### CODE REVIEW

**Comment by Nyr** [comment]
I have considered this, but what @lukebarone mentions is exactly why I didn't go ahead and implement it.

My idea was to allow the user to input comma-separated IPs, since it's very common to see DNS with multiple IP addresses. I can get this implemented but I think that it can be a bit confusing to the user.

The input would be something like this:

```
7) Custom

Please enter one or more IPv4 addresses separated by commas.
Example: 4.2.2.2,9.9.9.9
DNS :
```

What's the community sentiment? Would this be a desired feature? I hope that others can chime in and let us know their position.

I'm closing the pull request because if implemented, I'll do that my way.

PS: Raspbian is unsupported, even if it works.

**Comment by lukebarone** [comment]
I would love for that feature, but it needs to be easy, and reliable. I
like error checking, and would support changes that have proper error
checking.

**Comment by Nyr** [comment]
Is the dialog I'm proposing intuitive enough to the user? I think it's not great... if anyone can think of a better way, it can be considered.

Let's see what others think about this :)

**Comment by Lukas-Heiligenbrunner** [comment]
Hmmm...  I needed this feature for me, so i decided to program it...
I know at the moment it is not very user friendly programmed but in my opinion it would be a nice feature... (And  it worked for me) ((;
For the most incapable users it would be useful to check the entered ips...

If somebody of you knows a better way to implement this feel free and do it. ((;

**Comment by hfsyung** [comment]
Second one.

**Pull request closed without merging**
