### PR TITLE
use TLS-HMAC

### PR DESCRIPTION
**Pull request by phime42**
small PR according to https://openvpn.net/index.php/open-source/documentation/howto.html#security

### CODE REVIEW

**Comment by Nyr** [comment]
I considered this one in the past (after FREAK mainly) and had been wondering for a bit about it.

I agree that `tls-auth` adds an additional layer of security, but the usefulness is kinda limited for most use cases and I try to keep the script as barebones/default as possible, leaving personal preference or niche hardening out. This directive is not used by default in the sample OpenVPN configs so I will not implement it at this time.

Thank you anyway.

**Comment by user00036** [comment]
> 我过去曾考虑过这个问题（主要是在 FREAK 之后），并且一直想对此进行一些思考。
> 
> 我同意 `tls-auth`添加了额外的安全层，但对于大多数用例来说，实用性有点有限，我尝试尽可能使脚本保持准系统/默认状态，从而保留个人偏好或利基强化。 默认情况下，OpenVPN 配置示例中不使用该指令，因此我目前不会实现它。
> 
> 不管怎样，谢谢你。

Is it possible to give an option during installation to enable or disable tls-auth?

**Comment by Nyr** [comment]
@user00036 `tls-crypt`, which is an improvement over `tls-auth` is used by default for many years already.

**Comment by user00036** [comment]
> @user00036 `tls-crypt`，这是一个改进 `tls-auth`默认情况下已经使用了很多年。

ok,thanks

**Comment by user00036** [comment]
> @user00036 `tls-crypt`, which is an improvement over `tls-auth` is used by default for many years already.

Can you consider providing options to enable tls-crypt v2 and tls1.3? If openvpn is not supported, it seems to downgrade to tls-crypt v1 by default.

**Comment by TinCanTech** [comment]
@Nyr this user is also harassing Openvpn on github.

**Comment by Nyr** [comment]
@TinCanTech thank you as always for stepping by to provide context :)

**Comment by user00036** [comment]
> @Nyr该用户还在github上骚扰Openvpn。
> 
> [https://github.com/Openvpn/openvpn/issues?q=is%3Aissue+is%3Aclosed ](https://github.com/Openvpn/openvpn/issues?q=is%3Aissue+is%3Aclosed)
> 
> 您可以随意删除我的评论。



> @Nyr该用户还在github上骚扰Openvpn。
> 
> [https://github.com/Openvpn/openvpn/issues?q=is%3Aissue+is%3Aclosed ](https://github.com/Openvpn/openvpn/issues?q=is%3Aissue+is%3Aclosed)
> 
> 您可以随意删除我的评论。

Are you a fucking idiot? cerebral palsy

**Comment by user00036** [comment]
> @Nyr该用户还在github上骚扰Openvpn。
> 
> [https://github.com/Openvpn/openvpn/issues?q=is%3Aissue+is%3Aclosed ](https://github.com/Openvpn/openvpn/issues?q=is%3Aissue+is%3Aclosed)
> 
> 您可以随意删除我的评论。

Are you a fucking idiot? cerebral palsy

**Pull request closed without merging**
