### PR TITLE
Added the option for Quad9 DNS

### PR DESCRIPTION
**Pull request by dstinebaugh**
Adding option 7 to include the Fast and Secure DNS offering from
quad9.net

### CODE REVIEW

**Comment by Nyr** [comment]
Next time, use the search engine before submitting a pull request: #379.

**Comment by dstinebaugh** [comment]
Honestly it was faster for me to make the pull than to search out your post back in nov. 
Thanks for the attitude though. Just trying to help make your script better for a wider range of users.

**Comment by Pofilo** [comment]
The idea of the script is very good, but every PR helping and improving the script always result to the conclusion than the PR is useless ...

Maybe we should fork it !

**Comment by Nyr** [comment]
@Pofilo I would ask you to find any high-quality contribution or improvement which I have shot down over the years.

Yes, this pull request is useless because the inclusion of this DNS was already discussed and rejected, for very clear reasons already stated in the original issue. Additionally, the pull request would be useless anyway since its author forgot to include the secondary name server.

So yeah, not helpful so it was rejected, it's nothing personal.

**Pull request closed without merging**
