### PR TITLE
Update openvpn-install.sh

### PR DESCRIPTION
**Pull request by dmbekker**
Will halt the script if a command returns a error code >= 1
explained better [here](http://stackoverflow.com/questions/821396/aborting-a-shell-script-if-any-command-returns-a-non-zero-value#comment630464_821419)

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Should check before copy, like write a `copy` function, instead of ignore the error.

```bash
function copy()
{
    if [ -r $1 ]; then
        cp $1 $2
    else
        echo oops
    fi
}
```

**Comment by Nyr** [comment]
@PeterDaveHello the code isn't there anymore, got removed with the last commit.

**Comment by PeterDaveHello** [comment]
@Nyr I think in the current code, we could also use `-e`

**Comment by Nyr** [comment]
@PeterDaveHello I seriously doubt it, but don't want to try and ruin anything.

An example would be easy-rsa always throwing an error IIRC.

**Comment by PeterDaveHello** [comment]
Would you mind to tell me the line number?
https://github.com/Nyr/openvpn-install/blob/master/openvpn-install.sh

**Comment by Nyr** [comment]
Not really interested in losing my time arguing about something I written and tested during hours. easy-rsa throws an error, I think it was during certificate generation.

If you don't like it, fork.

**Comment by PeterDaveHello** [comment]
No offense, just wanna know the erro :smile:

**Pull request closed without merging**
