### PR TITLE
Updated instructions to download install script with HTTPS.

### PR DESCRIPTION
**Pull request by cmars**
My editor seems to want to add a newline to the last line. Not trying to mess with your donate link, promise!

### CODE REVIEW

**Comment by Nyr** [comment]
Are you by any chance **laumars** at Hacker News? Anyway, check #24 and #66.

I could still use HTTPS but just some months ago they didn't even have a valid certificate there. Now they do, but still not HSTS. If in the future they start using HSTS (so there is a "guarantee" that the valid certificate will be mantained), I'll be happy to switch to HTTPS, still with `--no-check-certificate` for the reasons already mentioned in the past.

**Comment by lmorg** [comment]
No he's not laumars. And HSTS has nothing to do with the validity of certificates. It's just a HTTP header that tells your browser to reconnect over SSL/TLS. In practical terms, it's little different to a 301 redirect.

The fact that you keep closing these issues is insane.  Either do your users a favour and add the following to your instructions, or close this repo and leave security software deployment to people who are security concious:

    $(which apt-get yum) install ca-certificates

**Comment by Nyr** [comment]
I know what HSTS is. It implies a compromise of continuity, which just a few months ago wasn't there with GitHub providing an invalid certificate. HSTS is very different than a simple redirect because it instructs further connections to be over SSL only and not even try plain text.

> Either do your users a favour and add the following to your instructions, or close this repo and leave security software deployment to people who are security concious

I propose a third option: you don't tell me what to do with my repo after all the hours of work/testing/support I've invested over the years to help people for free. I can consider suggestions, but I will not implement all of them. One-liners are always insecure by defaut, HTTPS or not.

**Comment by lmorg** [comment]
> HSTS is very different than a simple redirect because it instructs further connections to be over SSL only and not even try plain text.

That's not a big difference dude. And completely irrelevant in our discussion because `wget` would be connecting to Github for the first time and thus wouldn't have a `.wget-hsts` database created at that point.

> I can consider suggestions.

You're not though. That's the point. These issues have been raised a multitude of times and with a multitude of solutions and you've closed every single one of them arguing that it's perfectly fine to blindly pull down code over insecure connections and then run them as root. This is your pet project, I appreciate that. I'm just concerned that you're putting your users at unnecessary risk given the fix is *really* easy. At this point, I honestly think you're just closing these issues out of shear stubbornness since a few of us have offered some genuinely helpful suggestions. But at the end of the day this is your repo.

> One-liners are always insecure by defaut, HTTPS or not.

Not really. `$(which apt-get yum) install ca-certificates` actually improves the security as it means you don't need to disable SSL certificate checking. But we both know this is a futile discussion so I'll just leave you be :)

**Comment by Nyr** [comment]
> That's not a big difference dude. And completely irrelevant in our discussion

It is not. You don't seem to be understanding my point: HSTS would mean that GitHub will make sure to maintain a valid certificate there so it doesn't disappear in the future again like it did just a few months ago.

> You're not though.

I do consider all of the suggestions and pull requests. I just don't merge/implement all of them.

> it's perfectly fine to blindly pull down code over insecure connections and then run them as root

It is NOT fine to blindly pull down code over ANY connection and instantly run it as root. Don't put words in my mouth which I never used.

> the fix is really easy

None of the proposed fixes lack negative implications. The one proposed here has two that I can think of:
- No `apt-get update` before `install` means the one liner breaks under some conditions (like a fresh OS image at many virtualization providers).
- git.io isn't using SSL by default and HTTPS there has been already broken in the past.

Anyway: check e58addc2c5b8cbc75709d457a54b3ee50c6036e0. The one-liner is still there because of the above and because it is insecure anyway. I still consider reasonable to verify server certificates on the script itself, specially since the `ca-certificates` bundle is very prevalent anyway.

**Comment by lmorg** [comment]
> It is not. You don't seem to be understanding my point: HSTS would mean that GitHub will make sure to maintain a valid certificate there so it doesn't disappear in the future again like it did just a few months ago.

HSTS offers none of those guarantees though. It's just a HTTP header. Github could still break their SSL certs tomorrow even with HSTS enabled.

> It is NOT fine to blindly pull down code over ANY connection and instantly run it as root. Don't put words in my mouth which I never used.

That is exactly what your install instructions did though.

> None of the proposed fixes lack negative implications. The one proposed here has two that I can think of:
> * No apt-get update before install means the one liner breaks under some conditions (like a fresh OS image at many virtualization providers).

Fair point, though you can add that in too:

    pkg=$(which apt-get yum); $pkg update && $pkg install ca-certificates

(not that I'm advocating one liners either. Just following your lead on this one)

> * git.io isn't using SSL by default and HTTPS there has been already broken in the past.

To be fair, I recommended you do away with URL shortners even before I knew this. Between these SSL issues you've highlighted with git.io, and the way it breaks readability for the user (they can't prove it goes to your Github repository without accessing the link via one method or another), I personally don't think there's a sufficient benefit in the "it saves keystrokes" nor "it looks prettier" argument to justify it.

But I can at least sympathise why wanted the Github URL shortened :)

> Anyway: check e58addc.

Nice update :+1:

**Comment by Nyr** [comment]
> pkg=$(which apt-get yum); $pkg update && $pkg install ca-certificates

Unfortunately, `update` in `yum` = `upgrade` in `apt-get`. I can't think of a simple approach for the one-liner without an if/else.

Anyway, I plan to remove the `--no-check-certificate` and force HTTPS in the future. I'm just waiting for the templates missing `ca-certificates` to become more uncommon.

**Comment by lmorg** [comment]
`yum` does also have an `update` which does perform slightly differently to `apt-get update` and `yum upgrade`, but `yum update` would still work in this particular scenario.

**Comment by Nyr** [comment]
> but yum update would still work in this particular scenario

It would update other unrelated packages, so it is unacceptable.

**Comment by lmorg** [comment]
So does yum upgrade yet earlier you were advocating that.

In fact you _should_ be ensuring your users are running the latest patched software. But that's another issue from a long list of security vulnerabilities with your repo.

**Comment by Nyr** [comment]
> So does yum upgrade yet earlier you were advocating that.

False, I never said anything like that.

> In fact you should be ensuring your users are running the latest patched software. But that's another issue from a long list of security vulnerabilities with your repo.

No, no, no and no. I'm not going to force my users to upgrade/break their system, this scripts installs OpenVPN and that's it. I'm definitively not forcing an upgrade on anyone because that's not the expected outcome of an **OpenVPN installer**.

> long list of security vulnerabilities with your repo.

You've only listed one "vulnerability": a one-liner which is completely optional. Open a new issue if you find any reasonable vulnerability within `openvpn-install.sh` and I'll make sure to address it. Until then, don't waste more of my time.

**Pull request closed without merging**
