### PR TITLE
Update openvpn-install.sh

### PR DESCRIPTION
**Pull request by pnhat997**
plz add that line

### CODE REVIEW

**Comment by Nyr** [comment]
The `duplicate-cn` setting has been discussed in many other issues. This will not change.

**Comment by pnhat997** [comment]
your script is easy to use and i see most people want use vpn easy, create one openvpn profile and use for more device

**Comment by pnhat997** [comment]
> been

your script is easy to use and i see most people want use vpn easy, create one openvpn profile and use for more device

**Comment by Nyr** [comment]
I suggest that you create a new certificate for each device. That's how it should be done, except if you have a really good reason to do otherwise.

**Pull request closed without merging**
