### PR TITLE
multi-openvpn-install.sh

### PR DESCRIPTION
**Pull request by NextGenerationcloud**
sudo multi-openvpn-install.sh all  Fail
sudo multi-openvpn-install.sh 0  Fail
sudo multi-openvpn-install.sh 1  OK....  Server 1 + Full vpn +i-net
sudo multi-openvpn-install.sh 2 OK.... Server 2 vpn server to server no i-net

EN / DE

### CODE REVIEW

**Comment by Nyr** [comment]
Zero information about the commit, comments and even variables in German, a very substantial and undocumented rewrite... there is no way this will ever be merged to the mainline repo.

But of course you are more than welcome to maintain a fork for your use case (which seems to be integration with Nextcloud, some kind of control panel for self-hosted services?).

**Comment by SeymourRu** [comment]
I liked an idea of attempt to make this script multiinternational, perhaps it is not so bad at all yet it will be very handy for some ppl out there

**Comment by Nyr** [comment]
@SeymourRu of course it would be great to have the installer in many languages, but unfortunately I only speak English and Spanish.

So if I want to merge a commit translating the script to German or Russian, I would have two big issues:
- How can I ensure that all the translations are faithful and have good grammar?
- How can I find a person speaking all the supported languages every time that I need to modify anything?

I prefer to keep it simple, because I can't dedicate a lot of time to maintain this project (you can see that sometimes I need some days to reply to issues). And to be fair, anyone doing a little bit of system administration is expected to understand at least a little technical English.

**Comment by NextGenerationcloud** [comment]
Yes it is a multi server 
Yes, it can be cloud ^^
No, you can also use it normally ;)
language has been translated with Google translator 
If you only build the language, you do not do anything wrong ^^

**Comment by SeymourRu** [comment]
@Nyr There is no chance you can check correctness of translation unless you learn foreign language or pay someone qualified enough to do translation for you and even then you can not have 100% guarantee :)
It is a common case when community can help with translation and can be useful btw

What about system administration, I specially wrote word `some`, definetly meant non-sysadmins! This is more about ordinary users who just want to upgrade their security level or fight against censorship :)

**Comment by NextGenerationcloud** [comment]
and sorry I am XD beginner

**Pull request closed without merging**
