### PR TITLE
Fix: Generate DH pem instead of using hardcoded one

### PR DESCRIPTION
**Pull request by 255h**
Use openssl to create .pem instead of using hard-coded one.

### CODE REVIEW

**Comment by Nyr** [comment]
This does not "fix" anything.

**Comment by 255h** [comment]
Nothing, except private key disclosure...

**Comment by 255h** [comment]
Potential disclosure to be precise.
Use of same dh makes it vulnerable to offline pre-compute attack. This renders key exchange process unprotected if successful.
Using openly available ones across huge amount of devices is calling for a trouble. 

Yeah.. i know its all the theory and stuff. But using 512-bit primes was considered perfectly safe too back in days.
Anyway openvpn docs do recommend to generate prime numbers yourself for a reason.  Some standard even require DH parameters rotation....

**Comment by Nyr** [comment]
So this pull request does not fix a private key disclosure vulnerability or any other real world issue.

Also, merging this pull request would effectively break the installer in low end systems, because generating Diffie-Hellman parameters is very CPU intensive.

**Pull request closed without merging**
