### PR TITLE
Add OpenVPN over SSL to obfuscate OpenVPN traffic

### PR DESCRIPTION
**Pull request by birkhoffcheng**
As said in title, just added OpenVPN over SSL tunnel support, so the traffic looks like authentic HTTPS traffic even to deep packet inspection.

### CODE REVIEW

**Comment by birkhoffcheng** [comment]
Sorry, I changed most of README...... You can change back after.

**Comment by Nyr** [comment]
This will not be merged into the project. While I appreciate the work you have done to make the script work for your needs, there is a lot of unneeded stuff in this pull request. From taking a quick look, I would also suggest reading on how cipher selection and negotiation works with OpenVPN 2.4+, there is no need for some of your prompts, that stuff gets automatically solved.

I know this stunnel layer can be useful in some situations, but when possible, I am usually suggesting Shadowsocks and its variants to users in censored networks, both because its lower amount of overhead and because it is way more flexible to evade censorship. Of course you may still want a VPN instead of SOCKS in some of those situations.

That said, I would like to ask that you don't replace my copyright notice in your fork. You can modify everything else, but please keep the credits in your derivative works.

**Comment by DonZheng** [comment]
Hi @Nyr ,

Do you have any intention to officially support socks5 in your project? Even as an option for users to choose?

I'm sure there are quite a number of users out there crying for this, including myself.

Keep up the great work!

**Comment by Nyr** [comment]
@DonZheng if by SOCKS you mean OpenVPN over stunnel, that will never be supported by the script. Of course you can install OpenVPN using the script and then configure stunnel as you wish.

I have already discussed the implementation of anti-censorship techniques in other issues, but the bottom line is that it's a cat and mouse game which at the moment I don't have the resources to play. What works for one country doesn't for others and the situation is always evolving quickly. It is also difficult for me to be up to date as a foreigner, because there isn't a lot of information available in English from the most affected countries (China and Iran).

**Comment by libea18** [comment]
i need openvpn over SSL tunnel setup
how can i have script ?

**Pull request closed without merging**
